### PR TITLE
AGX first pass

### PR DESCRIPTION
**Pull request by erendrake**
I Reformatted your PR to be more like what we have for remotetech. 

i tested it and it still works :) how does this look to you?

### CODE REVIEW

**Comment by SirDiazo** [comment]
Looks fine to me, however I will admit the binding stuff went over my head.

The reflection stuff to AGX still looks good though.

However,  src/kOS/AddOns/ActionGroupsExtended/ActionGroupsExtendedAPI.cs Line 44 should change, currently:

/// <returns>The Action group state</returns>

should be:

/// <returns>Was the action activated</returns>

As there are several conditions, notably a vessel out of range and so not loaded, that can prevent AGX from activating actions on other vessels. Therefore I added that as feedback on if the action has activated.

**Comment by SirDiazo** [comment]
Okay, two things.

1) Where is documentation for this ending up? There are a couple gotchas that players need to be aware of. Nothing serious, but there are timing issues surrounding undocking and trying to activate actions in the same update frame.

2) I've added a "Script Trigger" action to the kOS control pods. This is a dummy action that does nothing but it acts as a place holder in AGX so that kOS can monitor that action group for the player to trigger it. If an action group does not have an action in it, AGX will always return that groups state as false otherwise. All code for this is in AGX and works by adding a ModuleKOSVoidAction via module manager. (AGX Version 1.29b or newer.)

**Comment by erendrake** [comment]
I made this a PR to your branch so you could merge it and it would show up in the kOS PR.

1 ) I think that we need a new top level in the documentation for "Addons" and we would have a document for each addon we integrate with. I would also add a mention to the bindings documentation. 

2 ) hmm i think ill have to see it. i am not opposed to adding new stuff in the kOS processor if that makes it simpler

**Comment by SirDiazo** [comment]
1) Alright. When this hits release, I'll type up something in the AGX thread and copy-paste that across for most of the documentation on the kOS side. On that note, I consider the AGX side of things release ready for the AG11 through AG250 bindings which is enough for the first release.

2) Here is the entire part module that I then use a MM script to add to every part that has the kOSProcessor module. https://github.com/SirDiazo/AGExt/blob/master/AGExt/kOSVoidAction
It is an empty place holder action to trick AGX into using the action group so it can be monitored by kOS scripts, it doesn't actually _do_ anything. As this only has a point when AGX is installed, I was thinking it should be part of the AGX install, not the kOS install.

**Comment by SirDiazo** [comment]
Conversation moved to https://github.com/KSP-KOS/KOS/pull/481

**Pull request merged**
